# Generated by Django 5.0.1 on 2024-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
